### PR TITLE
Das 232 Use Backend Libs

### PR DESCRIPTION
**Pull request by benshaw**
## Description
Get Hat working with backend libs and latest clients

# Blocked By
https://github.com/dataswift/backend-libraries/pull/48

## Details
* Add dependency on backend libs
* Remove transient dependencies from clients
* Update code to use models instead of clients for data models
* Update code to not use inheritance for models
* run scalafmt/scalasbt

## Type
- [ ] Bug Fix
- [ ] Feature Addition
- [X] Refactor
- [ ] HotFix

## Checklist
- [X] tested locally
- [X] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by xavji** [comment]
can we deploy this to dev to verify the correct behaviour ?

**Comment by benshaw** [comment]
> I deploy my feature branches on dev where I can do real end-to-end tests (AWS services + other Dataswift components), I don't trust local tests sorry...

Ok this is news to me i wasnt aware that the team had decided on this process, ill look at doing this

**Comment by benshaw** [comment]
> it was Piotr who did the work. It is done with github workflows see devdashboard for an example

I spoke to @pperzyna and he advised the only way to do this for HAT is to modify the github action
He advised that HAT CI/CD is not at the same level as dev portal and is challenging becuase it is open source

**Comment by benshaw** [comment]
@xavji can you please advise what i can do to unblock this PR

**Comment by xavji** [comment]
if you cannot see how to deploy without merging then I guess there is no choice...

**Comment by benshaw** [comment]
> if you cannot see how to deploy without merging then I guess there is no choice...

It has nothing todo with what i can see I am simply reporting what i have been told from our dev ops expert who i trust

**Comment by benshaw** [comment]
@xavji @dataswifty @whiteshadow-gr still waiting for approval on this PR

**Comment by whiteshadow-gr** [comment]
Aren't these reviewed? I remember a similar branch name.

**Comment by benshaw** [comment]
> Aren't these reviewed? I remember a similar branch name.

this has not been aprroved
i seperated the changes into 2 branches so it was easier to review
this one which applied the nescessasry changes (bring in backend libs etc)
and one which applied logging
generally i believe it is easire to review small changes rather than one big pr

**Review by whiteshadow-gr — COMMENTED** [review]
I saw some formatting issues, like no whitespace before and after the `{ }`. Also I think the imports should be alphabetically ordered automatically but this is not the case. Otherwise looks good to me!

**Comment by dataswifty** [comment]
> > if you cannot see how to deploy without merging then I guess there is no choice...
> 
> It has nothing todo with what i can see I am simply reporting what i have been told from our dev ops expert who i trust

We auto-deploy on merges to `dev` I'm fine with this going to the `dev` env for real environment testing.

**Review by dataswifty — APPROVED** [review]

**Comment by benshaw** [comment]
> I saw some formatting issues, like no whitespace before and after the `{ }`. Also I think the imports should be alphabetically ordered automatically but this is not the case. Otherwise looks good to me!

scalafix and scalfmt have all been run

**Review by xavji — APPROVED** [review]

**Pull request merged**
