### PR TITLE
DSE754 Complete migration to React-based dashboard

### PR DESCRIPTION
**Pull request by augustinas**
## Description
The PR updates and re-arranges frontend routes in order to remove PDA Dashboard v3 (based on Angular framework) and fully replace it with v4 (based on React framework). The main difference between the dashboard versions is frontend routing: Angular implementation was using [hash-based routing](https://angular.io/api/common/HashLocationStrategy) and the new version is using standard path based routing. In the PR we also remove all known unused frontend assets.

## Why 
The change is needed to support frontend's migration from Angular to React.

## AC
Change HAT server routing to serve React frontend only.

## Source
https://dswift.atlassian.net/browse/DSE-754

## Type
- [ ] Bug Fix
- [ ] Feature Addition 
- [x] Refactor
- [ ] HotFix

## Checklist
- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by leymytel — APPROVED** [review]
LGTM

**Comment by augustinas** [comment]
Sorry for the big PR, pretty much all of the deleted code comes from frontend assets that were unused and got removed.

**Comment by dataswifty** [comment]
I did not look at the changes to fonts, styles, just the conf, scala and JS.

**Review by dataswifty — APPROVED** [review]

**Review by benshaw — APPROVED** [review]
LGTM

**Pull request merged**
